[project]
name = "computationalcost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ace-tools>=0.0",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
]
