version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: company_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

