[package]
name = "csv_to_postgres"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
csv = "1"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }  # ← 追加！
