[project]
name = "macd-flask-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "yfinance>=0.2.63",
]
